config/routes.rb
Rails.application.routes.draw do

  get 'spots/index'
  get 'spots/show'
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  devise_for :users

  # ネストさせてる
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :fish do
    resources :spots, only: [:index, :show]
    resources :fish_comments, only: [:create, :destroy]
    resource :fish_favorites, only: [:create, :destroy]
  end


  resources :items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :fishes, dependent: :destroy
  has_many :fish_comments, dependent: :destroy
  has_many :fish_favorites, dependent: :destroy

  # フォローをした、されたの関係/class_name: "Relationship"でRelationshipテーブルを参照/foreign_key(外侮キー)で参照するカラムを指定しています
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  # 一覧画面で使う
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # フォロー・フォロワーの一覧画面で、user.followersという記述でフォロワーを表示したいので、throughでスルーするテーブル、sourceで参照するカラムを指定。

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if word == ""
      @user = []
    elsif search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  attachment :profile_image, destroy: false

  validates :name, presence: true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find(params[:id])
    @fish = @user.fishes

  end

  def index
    @users = User.all

  end

  def edit
    @user =User.find(params[:id])
    if @user.id == current_user.id
      render "edit"
    else
      redirect_to user_path
    end

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end

  end


   private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_info.html.erb
 <div class="container-fluid">
    <div class="jumbotron">
      <div class="row">
        <div class="col-md-2 col-xs-12 col-sm-4 ">
          <%= attachment_image_tag user, :profile_image, :fill, 300, 300, format: 'jpeg', fallback: "img/no_image.jpg", size:'100x100', class:"img-thumbnail rounded-circle" %>
        </div>
        <div class="col-md-10 col-xs-12 col-sm-8 ">
          <div class="container" style="border-bottom:1px solid black">
            <h3><i class="fas fa-user-circle"></i><%= user.name %></h3>
            <tr>
              <th>follows</th>
              <th><%= link_to user.followings.count, user_followings_path(user.id) %></th>
            </tr>
            <tr>
              <th>followers</th>
              <th><%= link_to user.followers.count, user_followers_path(user.id) %></th><br>
            </tr>
         </div>
          <tr>
            <th><h5>~紹介文~</h5></th>
            <th><%= user.introduction %></th><br>
          </tr>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete,class: "btn  btn-danger" %>
            <% else %>
               <%= link_to "フォローする", user_relationships_path(user.id), method: :post,class: "btn  btn-primary" %>
            <% end %>
          <% end %>
          <% if user_signed_in? && user == current_user %>
            <%= link_to '新規釣果投稿',new_fish_path(user),class: "btn  btn-primary fas fa-fish" %>
            <%= link_to '新規アイテム投稿',new_item_path(user),class: "btn  btn-info fas fa-tools" %>
            <%= link_to 'アイテムBox',items_path(user),class: "btn  btn-success  fas fa-toolbox" %>
            <%= link_to '編集画面',edit_user_path(user),class: "btn btn-warning fas fa-user-cog edit_user_#{user.id}" %>
          <% else %>
            <%= link_to 'アイテムBox',items_path(user),class: "btn  btn-success  fas fa-toolbox" %>
          <% end %>
        </div>
      </div>
    </div>
 </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
    <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">ユーザー編集フォーム</h5>
      <div class="form-body p-4">
        <label class="input-label">現在のアイコン画像</label>
        <%= attachment_image_tag @user, :profile_image, :fill, 200, 200, format: "jpeg", fallback: "no_image.jpg", size:'200x200', class:"img-thumbnail rounded-circle" %>
        <%= form_with model: @user, url: user_path(@user.id), local: true do |f| %>
          <label class="input-label">新規アイコン画像</label>
          <%= f.attachment_field :profile_image, class: "w-100" %>
          <label class="input-label">ユーザー名</label>
          <%= f.text_area :name, class:"form-control" %>
          <label class="input-label">紹介文</label>
          <%= f.text_area :introduction, class:"form-control", rows:"4" %>
          <hr>
          <%= f.submit '編集する', class:"btn btn-lg btn-block btn-warning mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
 <h1 class="index-title">Users 一覧</h1>
 <div class="container">
    <div class="row">
       <% @users.reverse.each do |user| %>
        <div class="col-lg-3 col-md-4 thumb">
          <%= link_to user_path(user) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size:"200x200", class: "fluid img-thumbnail rounded-circle" %><br>
            <i class="fas fa-user-circle"></i><%= user.name %>
          <% end %>
        </div>
      <% end %>
    </div>
 </div>

app/views/users/show.html.erb
<div class="container-fluid">
    <div class="jumbotron">
      <div class="row">
        <div class="col-md-2 col-xs-12 col-sm-4 ">
          <%= attachment_image_tag @user, :profile_image, :fill, 400, 400, format: 'jpeg', fallback: "no_image.jpg", size:'100x100', class:"img-thumbnail rounded-circle" %>

        </div>
        <div class="col-md-10 col-xs-12 col-sm-8 ">
          <div class="container" style="border-bottom:1px solid black">
            <h3><i class="fas fa-user-circle"></i><%= @user.name %></h3>
            <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_followings_path(@user.id) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_followers_path(@user.id) %></th><br>
          </tr>
          </div>
          <tr>
            <th><h5>~紹介文~</h5></th>
            <th><%= @user.introduction %></th><br>
          </tr>
          <% if current_user != @user %>
            <% if current_user.following?(@user) %>
              <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete,class: "btn  btn-danger" %>
            <% else %>
               <%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class: "btn  btn-primary" %>
            <% end %>
          <% end %>
          <% if user_signed_in? && @user == current_user %>
            <%= link_to '  新規釣果投稿',new_fish_path(@user),class: "btn  btn-primary fas fa-fish" %>
            <%= link_to '  新規アイテム投稿',new_item_path(@user),class: "btn  btn-info fas fa-tools" %>
            <%= link_to '  アイテムBox',items_path(@user),class: "btn  btn-success  fas fa-toolbox" %>
            <%= link_to '  編集画面',edit_user_path(@user),class: "btn btn-warning fas fa-user-cog edit_user_#{@user.id}" %>
          <% else %>
            <%= link_to 'アイテムBox',items_path(@user),class: "btn  btn-success  fas fa-toolbox" %>
          <% end %>
        </div>
      </div>
    </div>
 </div>
<%= render 'fish/index', fish: @fish %>