config/routes.rb
Rails.application.routes.draw do

  get 'spots/index'
  get 'spots/show'
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  devise_for :users

  # ネストさせてる
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :fish do
    resources :spots, only: [:index, :show]
    resources :fish_comments, only: [:create, :destroy]
    resource :fish_favorites, only: [:create, :destroy]
  end


  resources :items

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
   before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    elsif @range == "Fish"
      @fish = Fish.looks(params[:search], params[:word])
    else
      @items = Item.looks(params[:search], params[:word])
    end
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
<div class="container-fluid bg-dark">
  <div class="row">
    <div class="col-md-5 ml-auto search_form">
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <%= f.text_field :word %>
        <%= f.select :range, options_for_select([['User'], ['Fish'], ['Item']]), {include_blank: true} %>
        <%= f.select :search, options_for_select([["部分一致","partial_match"],["完全一致","perfect_match"]]) %>
        <%= f.submit "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
    </div>
  </div>
<% end %>

app/views/searches/search.html.erb
<table class="table table-hover table-inverse">
  <% if !params[:range].blank? && params[:word] == "" %>
    <p>検索結果はありません.</p>
  <% end %>
  <!--検索対象モデルがUserの時 -->
  <% if @range == "User" %>
   <h1>User 検索結果</h1>
   <div class="container">
      <div class="row">
         <% @users.reverse.each do |user| %>
          <div class="col-lg-3 col-md-4 thumb">
            <%= link_to user_path(user) do %>
              <%= attachment_image_tag user, :profile_image, :fill, 430, 400, format: 'jpeg', fallback: "no_image.jpg", size:"200x200", class: "fluid img-thumbnail rounded-circle" %><br>
              <i class="fas fa-user-circle"></i><%= user.name %>
            <% end %>
          </div>
        <% end %>
      </div>
   </div>
  <% elsif @range == "Fish" %>
    <h1>Fish 検索結果</h1>
    <div class="container">
       <div class="row">
         <% @fish.reverse.each do |fish| %>
           <div class="col-lg-3 col-md-4 thumb">
             <%= link_to fish_path(fish) do %>
                <%= attachment_image_tag fish, :image, :fill, 430, 300, format: 'jpeg', class: "fluid img-thumbnail" %>
             <% end %>
           </div>
         <% end %>
       </div>
    </div>
  <% elsif @range == "Item" %>
    <h1>Item 検索結果</h1>
    <div class="container">
       <div class="row">
         <% @items.reverse.each do |item| %>
           <div class="col-lg-3 col-md-4 thumb">
             <%= link_to item_path(item) do %>
               <%= attachment_image_tag item, :item_image, :fill, 430, 300, format: 'jpeg', class: "fluid img-thumbnail" %>
             <% end %>
           </div>
         <% end %>
    	 </div>
    </div>
  <% else %>
    <h3>検索に該当する投稿はありませんでした。</h3>
  <% end %>
</table>