config/routes.rb
Rails.application.routes.draw do

  get 'spots/index'
  get 'spots/show'
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  devise_for :users

  # ネストさせてる
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :fish do
    resources :spots, only: [:index, :show]
    resources :fish_comments, only: [:create, :destroy]
    resource :fish_favorites, only: [:create, :destroy]
  end


  resources :items

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :user
  attachment :item_image
  
  validates :name, presence: true
  validates :status, presence: true
  validates :item_image, presence: true

  def self.looks(search, word)
    if word == ""
      @item = []
    elsif search == "perfect_match"
      @item = Item.where("name LIKE?","#{word}")
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%")
    else
      @item = Item.all
    end
  end



  enum status: {
    retention: 0, #保有
    lost: 1, #ロスト
    want: 2, #欲しい

  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user_id = current_user.id
    if @item.save
      redirect_to item_path(@item), notice: "アイテムが新しく登録されました!!"
    else
      render 'new'
    end
  end


  def show
    @item = Item.find(params[:id])
    @user = @item.user
  end

  def index
    if params[:format].present?
      @user = User.find(params[:format])
      @items = @user.items
    else
      @items = Item.all
    end
  end

  def edit
    @item = Item.find(params[:id])
    if @item.user.id == current_user.id
      render "edit"
    else
      redirect_to items_path
    end
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to item_path(item.id)
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to items_path
  end

  private

   def item_params
    params.require(:item).permit(:item_image, :name, :body, :status)

   end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">アイテム編集フォーム</h5>
      <div class="form-body p-4">
        <% if @item.errors.any? %>
          <%= @item.errors.count %>件のエラーが発生しました
          <% @item.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <label class="input-label">現在の画像</label>
        <%= attachment_image_tag @item, :item_image, :fill, 200, 200, format: "jpeg", class:"img-thumbnail" %>
        <%= form_with model: @item, url: item_path(@item.id), local: true do |f| %>
          <label class="input-label">アイテム画像</label>
          <%= f.attachment_field :item_image, class: "w-100" %>
          <label class="input-label">アイテム名</label>
          <%= f.text_area :name, class:"form-control" %>
          <label class="input-label">紹介文</label>
          <%= f.text_area :body, class:"form-control", rows:"4" %>
          <label class="status">所有ステータス</label><br>
          <%= f.select :status, Item.statuses.map { |k,v| [I18n.t("enum.item.status.#{k}"), k]}  %>
          <hr>
          <%= f.submit '編集する', class:"btn btn-lg btn-block btn-warning mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<h1 class="index-title">Items 一覧</h1>
<div class="container">
   <div class="row">
     <% @items.reverse.each do |item| %>
       <div class="col-lg-3 col-md-4 thumb">
         <%= link_to item_path(item) do %>
           <%= attachment_image_tag item, :item_image, :fill, 350, 300, format: 'jpeg', class: "fluid img-thumbnail" %>
         <% end %>
       </div>
     <% end %>
	 </div>
</div>

app/views/items/new.html.erb
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
  <% @item.errors.full_messages.each do |message| %>
   <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">アイテム投稿フォーム</h5>
      <div class="form-body p-4">
        <%= form_with model: @item, url: items_path, local:true do |f| %>
         <label class="input-label">アイテム画像</label>
          <%= f.attachment_field :item_image, class: "w-100" %>

          <label class="input-label">ルアー名</label>
          <%= f.text_area :name, class:"form-control", placeholder:"釣具などもOK！" %>
          <label class="input-label">コメント記入欄</label>
          <%= f.text_area :body, class:"form-control", rows:"4", placeholder:"コメント記入欄" %>
          <label class="input-label">所有ステータス</label><br>
          <%= f.select :status, Item.statuses.map { |k,v| [I18n.t("enum.item.status.#{k}"), k]} %>
          <hr>
          <%= f.submit '新規投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="post-detail py-5 bg-light">
  <div class="card w-75 mx-auto mt-4 shadow-lg">
    <%= attachment_image_tag @item, :item_image, class:"card-img-top"; %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= link_to user_path(@user.id) do %>
           <%= attachment_image_tag @item.user, :profile_image, :fill, 60, 60,format: 'jpeg', fallback: "no_image.jpg", size:'100x100', class:"mt-3 rounded-circle"; %>
          <% end %>
        </div>
        <div class="col-9">
          <p class="card-title">
          <strong><i class="fas fa-tools"></i>：<span> <%= @item.name %></span></strong>
          </p>
          <p class="card-title "><i class="fas fa-comment-dots"></i>：<%= @item.body %></p>
          <i class="fas fa-shopping-cart"></i>：<%= I18n.t("enum.item.status.#{@item.status}")%></p>
          <%= link_to user_path(@user.id) do %>
            <span><i class="fas fa-user-circle"></i> by <%= @item.user.name %> </span>
          <% end %>
          <span><i class="fa fa-calendar"></i> <%= @item.created_at.strftime('%Y/%m/%d') %></span><br>
          <% if @item.user == current_user %>
            <%= link_to edit_item_path(@item.id) do %>
              <button type="button" class="btn btn-warning"> 編集する </button>
            <% end %>
            <%= link_to item_path(@item.id), method: :delete, "data-confirm"  => "本当に投稿を削除しますか？"  do %>
              <button type="button" class="btn btn-danger"> 削除する </button>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>