config/routes.rb
Rails.application.routes.draw do

  get 'spots/index'
  get 'spots/show'
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  get "search" => "searches#search"
  devise_for :users

  # ネストさせてる
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :fish do
    resources :spots, only: [:index, :show]
    resources :fish_comments, only: [:create, :destroy]
    resource :fish_favorites, only: [:create, :destroy]
  end


  resources :items

end

app/models/fish.rb
class Fish < ApplicationRecord
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  has_many :fish_comments, dependent: :destroy
  has_many :fish_favorites, dependent: :destroy
  has_many :spots, dependent: :destroy

  attachment :image

  validates :fish_name, presence: true
  validates :lure, presence: true
  validates :address, presence: true
  validates :image, presence: true

  def fish_favorited_by?(user)
    fish_favorites.where(user_id: user.id).exists?
  end

  def self.looks(search, word)
    if word == ""
      @fish = []
    elsif search == "perfect_match"
      @fish = Fish.where("fish_name LIKE?","#{word}")
    elsif search == "partial_match"
      @fish = Fish.where("fish_name LIKE?","%#{word}%")
    else
      @fish = Fish.all
    end
  end


end

app/controllers/fish_controller.rb
class FishController < ApplicationController

  def new
    @fish = Fish.new
  end


  def create
    @fish = Fish.new(fish_params)
    @fish.user_id = current_user.id
    if fish_params[:address] == ""
       flash[:notice] = "ポイントを記入してください。"
       render :new and return
    end
    results = Geocoder.search(fish_params[:address])
    lat, lng = results.first.coordinates
    @fish.latitude = lat
    @fish.longitude = lng
    if @fish.save
      redirect_to fish_path(@fish), notice: "新規投稿が完了しました！"
    else
      render 'new'
    end
  end

  def show
    @fish = Fish.find(params[:id])
    @fish_comment = FishComment.new
    @user = @fish.user

  end

  def fish
    results = Geocoder.search(params[:address])
    @latlng = results.first.coordinates
    # これでmap.js.erbで、経度緯度情報が入った@latlngを使える。

    # respond_to以下の記述によって、
    # remote: trueのアクセスに対して、
    # map.js.erbが変えるようになります。
    respond_to do |format|
     format.js
    end
  end

  def index
    @fish = Fish.all
  end

  def edit
    @fish = Fish.find(params[:id])
    if @fish.user.id == current_user.id
      render "edit"
    else
      redirect_to fish_index_path
    end
  end

  def update
    @fish = Fish.find(params[:id])
    if fish_params[:address] == ""
       flash[:notice] = "ポイントを記入してください。"
     render :edit and return
    end
    results = Geocoder.search(fish_params[:address])
    lat, lng = results.first.coordinates
    @fish.update(fish_params.merge(latitude: lat, longitude: lng))
    redirect_to fish_path(@fish.id)
  end

  def destroy
    fish = Fish.find(params[:id])
    fish.destroy
    redirect_to fish_index_path
  end


  private

   def fish_params
    params.require(:fish).permit(:image, :fish_name, :lure, :body, :address, :latitude, :longitude)
   end

end

app/controllers/fishes_controller.rb
class FishesController < ApplicationController

  def new
    @fish = Fish.new
  end


  def create
    @fish = Fish.new(fish_params)
    @fish.user_id = current_user.id
    if @fish.save
      redirect_to fish_path(@fish), notice: "You have created fish successfully."
    else
      @fish = Fish.all
      render 'index'
    end
  end

  def index
  end

  def show
  end

  def edit
  end

  private

   def fish_params
    params.require(:fish).permit(:image, :fish_name, :lure, :body)

   end

end

app/helpers/fishes_helper.rb
module FishesHelper
end

app/views/fish/_index.html.erb
<h1 class="index-title">Fishes 一覧</h1>
<div class="container">
   <div class="row">
     <% fish.reverse.each do |fish| %>
       <div class="col-lg-3 col-md-4 thumb">
         <%= link_to fish_path(fish) do %>
            <%= attachment_image_tag fish, :image, :fill, 360, 300, format: 'jpeg', class: "fluid img-thumbnail" %>
         <% end %>
       </div>
     <% end %>
   </div>
</div>

app/views/fish/edit.html.erb
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">釣果編集フォーム</h5>
      <div class="form-body p-4">
        <% if @fish.errors.any? %>
          <%= @fish.errors.count %>件のエラーが発生しました
          <% @fish.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <label class="input-label">現在の投稿画像</label>
        <%= attachment_image_tag @fish, :image, :fill, 200, 200, format: "jpeg", class:"img-thumbnail" %>
        <%= form_with model: @fish, local:true do |f| %>
         <label class="input-label">釣果画像</label>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-fish"></i></span>
            </div>
            <%= f.text_field :fish_name, class:"form-control", placeholder:"魚種名" %>
          </div>
          <label class="input-label">ルアー名</label>
          <%= f.text_area :lure, class:"form-control", placeholder:"ルアー名" %>
          <label class="input-label">本文</label>
          <%= f.text_area :body, class:"form-control", rows:"4", placeholder:"本文記入欄" %>
          <label class="input-label">ポイント</label>
          <input id="address" type="textbox" value="" placeholder="入力後検索で確認">
          <input type="button" value="検索" onclick="codeAddress(<%= @fish.latitude %>, <%= @fish.longitude %>)">
          <input type="hidden" name="fish[address]" id="hidden_address">
          <hr>
          <%= f.submit '編集する', class:"btn btn-lg btn-block btn-warning mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id='map'></div>
<style>
#map{
  height: 400px;
}
</style>

<script>

  function init() {
     let map
     let geocoder

    geocoder = new google.maps.Geocoder()

    map = new google.maps.Map(document.getElementById('map'), {
      center: {
        lat: <%=@fish.latitude%>,
        lng: <%=@fish.longitude%>
      },
      zoom: 12
    });

    pos = new google.maps.LatLng(
    <%=@fish.latitude%>, //latitude
    <%=@fish.longitude%> //longitude
    );
    default_marker = new google.maps.Marker({
    map: map,
    position: pos,
    icon: {
    url: 'https://maps.google.com/mapfiles/kml/paddle/red-stars.png', //アイコンのURL
    scaledSize: new google.maps.Size(45, 40) //サイズ
    }
    });
  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=init" async defer></script>

app/views/fish/fish.js.erb
(function(){
  // 位置情報をもつ変数を用意
  let pos = new google.maps.LatLng(
   <%= @latlng[0] %>, //latitude
   <%= @latlng[1] %>  //longitude
  );

  mapInstance.setCenter(pos)
  let marker = new google.maps.Marker({
    map: mapInstance,
    position: pos
  });
})()

app/views/fish/index.html.erb
<%= render 'fish/index', fish: @fish %>

app/views/fish/new.html.erb
<% if @fish.errors.any? %>
  <%= @fish.errors.count %>件のエラーが発生しました
  <ul>
  <% @fish.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-7 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">釣果投稿フォーム</h5>
      <div class="form-body p-4">
        <%= form_with model: @fish, local:true do |f| %>
         <label class="input-label">釣果画像</label>
          <%= f.attachment_field :image, class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <div class="input-group-prepend">
              <span class="input-group-text" aria-hidden="true"><i class="fas fa-fish"></i></span>
            </div>
            <%= f.text_field :fish_name, class:"form-control", placeholder:"魚種名" %>
          </div>
          <label class="input-label">ルアー名</label>
          <%= f.text_area :lure, class:"form-control", placeholder:"ルアー名" %>
          <label class="input-label">コメント記入欄</label>
          <%= f.text_area :body, class:"form-control", rows:"4", placeholder:"コメント記入欄" %>
          <label class="input-label">ポイント</label><br>
          <input id="address" type="textbox" value="" placeholder="入力後検索で確認">
          <input type="button" value="検索" onclick="codeAddress()">
          <input type="hidden" name="fish[address]" id="hidden_address">
          <hr>
          <%= f.submit '新規投稿', class:"btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div id='map'></div>
<style>
#map{
  height: 400px;
}
</style>

<script>



    function initMap() {
      let map
      let geocoder
      geocoder = new google.maps.Geocoder()

      map = new google.maps.Map(document.getElementById('map'), {
        center: {
          lat: 35.681,
          lng: 139.767
        },
        zoom: 12
      });
    }
  function codeAddress() {
      let map
      map = new google.maps.Map(document.getElementById('map'), {
        center: {
          lat: 35.681,
          lng: 139.767
        },
        zoom: 12
      });
      let inputAddress = document.getElementById('address').value;
      let geocoder
      geocoder = new google.maps.Geocoder()

      geocoder.geocode({
        'address': inputAddress
      }, function (results, status) {
        if (status == 'OK') {
          map.setCenter(results[0].geometry.location);

        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location
        });


          // 検索値を隠しデータとしてセット
        let hidden_address = document.getElementById('hidden_address');
        console.log(hidden_address)
          hidden_address.setAttribute("value", inputAddress);
        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      });

    }


</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>

app/views/fish/show.html.erb
<div class="post-detail py-5 bg-light">
  <div class="card w-75 mx-auto mt-4 shadow-lg">
    <%= attachment_image_tag @fish, :image, class:"card-img-top"; %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= link_to user_path(@user.id) do %>
           <%= attachment_image_tag @fish.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", size:"150x150", class:"mt-3 rounded-circle"; %>
          <% end %>
        </div>
        <div class="col-10">
          <p class="card-title"><strong><i class="fas fa-fish"></i>：<span> <%= @fish.fish_name %></span></strong></p>
          <p class="card-title "><i class="fas fa-drumstick-bite"></i>：<%= @fish.lure %></p>
          <p class="card-title "><i class="fas fa-comment-dots"></i>：<%= @fish.body %></p>
          <p class="card-title "><i class="fas fa-anchor"></i>：<%= @fish.address %></p>
          <%= link_to user_path(@user.id) do %>
            <span><i class="fas fa-user-circle"></i> by <%= @fish.user.name %></span>
          <% end %>
          <span> ｜ <i class="fa fa-calendar"></i> <%= @fish.created_at.strftime('%Y/%m/%d') %> ｜ </span>
          <span><i class="fa fa-comment"></i> <%= link_to "#{@fish.fish_comments.count}", fish_path(@fish.id), class:"text-dark" %> ｜ </span>
          <span id="favorite_btn_<%= @fish.id %>">
            <%= render "fish_favorites/favorite", fish: @fish %>
          </span>
          <% if @fish.user == current_user %>
            <%= link_to edit_fish_path(@fish.id) do %>
              <button type="button" class="btn btn-warning"> 編集する </button>
            <% end %>
            <%= link_to fish_path(@fish.id), method: :delete, "data-confirm"  => "本当に投稿を削除しますか？"  do %>
              <button type="button" class="btn btn-danger"> 削除する </button>
            <% end %>
          <% end %>
          <div>
            <% @fish.fish_comments.each do |fish_comment| %>
              <hr>
              <%= link_to user_path(@user.id) do %>
               <%= fish_comment.user.name %>
              <% end %>
              <%= fish_comment.created_at.strftime('%Y/%m/%d') %>  /  <i class="fa fa-comment"></i>  :  <%= fish_comment.comment %>
              <% if fish_comment.user == current_user %>
                <div>
                  <%= link_to "コメント削除", fish_fish_comment_path(fish_comment.fish, fish_comment), method: :delete %>
                </div>
              <% end %>
            <% end %>
          </div>
          <div>
            <%= form_with(model:[@fish, @fish_comment], local: true) do |f| %>
              <%= f.text_area :comment, rows:'2',placeholder: "コメントをここに" %>
              <%= f.submit "送信する" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<h2 class="point">釣れたポイント</h2>
<!-- form_withはデフォルトでremote: trueの挙動になります -->
<div class="map_wrapper">
  <div id="map" class="gmap"></div>
</div>

<style>
#map{
  height: 600px;
}
</style>

<script>


 function initMap() {
   let mapInstance
   let geocoder
    // 変数を追加
   let marker
   geocoder = new google.maps.Geocoder()

    // 変数の名前をmapInstanceに変更、デフォルト位置を東京に変更
   mapInstance = new google.maps.Map(document.getElementById('map'), {
    center: {
      lat: <%=@fish.latitude%>,
      lng: <%=@fish.longitude%>
    },
    zoom: 10
 });

 // 保存された地図情報からピンをさす
    // google.maps.LatLngインスタンスを生成
    pos = new google.maps.LatLng(
    <%=@fish.latitude%>, //latitude
    <%=@fish.longitude%> //longitude
    );
    default_marker = new google.maps.Marker({
    map: mapInstance,
    position: pos,
    icon: {
    url: 'https://maps.google.com/mapfiles/kml/paddle/red-stars.png', //アイコンのURL
    scaledSize: new google.maps.Size(45, 40) //サイズ
    }
    });



  }

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap" async defer></script>